// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "effect",
  id: "skymen_SampleBackground",
  name: "Sample Background",
  version: "1.0.0.5",
  category: "blend",
  // "distortion",
  // "normal-mapping",
  // "tiling",
  // "other",
  // "color",
  author: "skymen",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Description",
  supportedRenderers: ["webgl", "webgl2", "webgpu"],
  blendsBackground: true,
  usesDepth: false,
  crossSampling: false,
  preservesOpaqueness: false,
  animated: false,
  mustPredraw: false,
  extendBox: {
    horizontal: 0,
    vertical: 0,
  },
  isDeprecated: false,
  parameters: [
    /*
    {
      type:
        "float"
        "percent"
        "color"
      ,
      id: "property_id",
      value: 0,
      uniform: "uPropertyId",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Property Name",
      desc: "Property Description",
    }
    */
    {
      type: "float",
      id: "mix",
      value: 1,
      uniform: "mixSlider",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Mix",
      desc: "Mix between the original and the effect",
    },
  ],
};
